name = "PaperData"
uuid = "e628e4c0-00d0-11ec-12e1-195979be6846"
authors = ["Marta Vanin"]
version = "0.0.1"

[deps]
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
PowerModelsDistributionStateEstimation = "d0713e65-ce0c-4a8e-a1da-2ed737d217c5"

[compat]
PowerModelsDistribution = "0.10.0"
PowerModelsDistributionStateEstimation = "0.2.3"
